FROM nvidia/cuda:9.0-cudnn7-devel-ubuntu16.04

# Set up user account and miniconda
ARG CONDA_DIR=/opt/conda
ARG USERNAME=mengcz
ARG USERID=1022

RUN apt-get update && \
  apt-get install -y --no-install-recommends \
  build-essential cmake git curl ca-certificates libjpeg-dev libpng-dev wget unzip sudo tmux vim-nox openssh-server sshfs && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/* && \
  curl -o ~/miniconda.sh -O  https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh && \
  chmod +x ~/miniconda.sh && \
  ~/miniconda.sh -b -p ${CONDA_DIR} && \
  rm ~/miniconda.sh && \
  useradd --create-home -s /bin/bash --no-user-group -u $USERID $USERNAME && \
  mkdir /workspace && \
  chown $USERNAME ${CONDA_DIR} -R && \
  chown $USERNAME /workspace -R && \
  adduser $USERNAME sudo && \
  echo "$USERNAME ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

# copy jupyter config
RUN mkdir /home/${USERNAME}/.jupyter
COPY jupyter_notebook_config.py /home/${USERNAME}/.jupyter/
RUN chown ${USERNAME} /home/${USERNAME} -R

# run following commands as non-root user
USER ${USERNAME}
WORKDIR /home/${USERNAME}
ENV PATH /opt/conda/bin:$PATH

# install python packages
RUN pip install pyyaml tensorboardX geopy networkx tqdm && \
  conda install pytorch==1.1.0 torchvision==0.2.2 cudatoolkit=9.0 -c pytorch && \
  conda install -y matplotlib scipy pandas jupyter scikit-learn geopandas && \
  conda install -y -c conda-forge jupyterlab igl meshplot

# install pytorch_geometric
ENV PATH /usr/local/cuda/bin:$PATH
ENV CPATH /usr/local/cuda/include:$CPATH
ENV LD_LIBRARY_PATH /usr/local/cuda/lib64:$LD_LIBRARY_PATH
RUN pip install --verbose --no-cache-dir torch-scatter==1.2.0 && \
  pip install --verbose --no-cache-dir torch-sparse==0.4.0 && \
  pip install --verbose --no-cache-dir torch-cluster==1.3.0 && \
  pip install --verbose --no-cache-dir torch-spline-conv==1.1.0 && \
  pip install torch-geometric==1.1.2 && \
  pip install -I numpy==1.16.2 # specify numpy==1.16.2 to avoid loading error (>=1.16.3 may require allow_pickle=True in np.load)

WORKDIR /workspace
